# Generated by Django 4.2.5 on 2023-10-07 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('symptons', models.TextField()),
                ('ssn', models.PositiveIntegerField(unique=True)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(130), django.core.validators.MinValueValidator(0)])),
                ('weight', models.PositiveIntegerField(max_length=4)),
                ('allergies', models.TextField()),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('patients', models.ManyToManyField(to='DoctorPortal.patient')),
            ],
        ),
    ]
