# Generated by Django 4.2.5 on 2023-10-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorPortal', '0003_remove_doctor_patients_alter_doctor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffID', models.IntegerField(default=-1)),
                ('patientID', models.IntegerField(default=-1)),
                ('updaterID', models.IntegerField(default=-1)),
                ('AccessLevel', models.CharField(choices=[('A', 'Admin'), ('V', 'Viewer')], default='V', max_length=1)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(to='DoctorPortal.patient'),
        ),
    ]
