# Generated by Django 4.2.5 on 2023-10-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DoctorPortal", "0004_patientdoctor_doctor_patients"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="username",
            field=models.CharField(default="", max_length=100),
        ),
    ]
