# Generated by Django 4.2.5 on 2023-10-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DoctorPortal", "0007_patient_last_login_alter_patient_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="symptons",
            new_name="symptoms",
        ),
    ]
