# Generated by Django 4.2.5 on 2023-10-23 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DoctorPortal", "0009_alter_patient_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="patients",
        ),
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.PositiveIntegerField(
                default=None,
                validators=[
                    django.core.validators.MaxValueValidator(130),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="allergies",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="patient",
            name="history",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="patient",
            name="symptoms",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="patient",
            name="weight",
            field=models.PositiveIntegerField(
                default=None,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2000),
                ],
            ),
        ),
    ]
