# Generated by Django 4.2.5 on 2023-10-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DoctorPortal", "0010_remove_doctor_patients_alter_patient_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="allergies",
            field=models.TextField(default="na"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="history",
            field=models.TextField(default="na"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="symptoms",
            field=models.TextField(default="na"),
        ),
    ]
