# Generated by Django 4.2.5 on 2023-10-24 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DoctorPortal", "0011_alter_patient_allergies_alter_patient_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="password",
            field=models.CharField(default="", max_length=25),
        ),
        migrations.AddField(
            model_name="doctor",
            name="patients",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialty",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="doctor",
            name="username",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="fname",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="lname",
            field=models.CharField(default="", max_length=50),
        ),
    ]
