# Generated by Django 4.2.5 on 2023-10-24 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DoctorPortal", "0013_patient_is_doctor_patient_is_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientdoctor",
            name="patientID",
        ),
        migrations.RemoveField(
            model_name="patientdoctor",
            name="staffID",
        ),
        migrations.RemoveField(
            model_name="patientdoctor",
            name="updaterID",
        ),
        migrations.AddField(
            model_name="patientdoctor",
            name="patient",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patientUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientdoctor",
            name="staffUser",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctorUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientdoctor",
            name="updaterUsername",
            field=models.CharField(default="", max_length=100),
        ),
    ]
