# Generated by Django 4.2.5 on 2023-10-24 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DoctorPortal", "0014_remove_patientdoctor_patientid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updaterUsername", models.CharField(default="", max_length=100)),
                ("apptDate", models.DateTimeField(auto_now_add=True)),
                ("docNotes", models.TextField(default="na")),
                ("patientNotes", models.TextField(default="na")),
                (
                    "patient",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apptPatient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staffUser",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendingDoctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
