# Generated by Django 4.2.5 on 2023-10-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DoctorPortal", "0015_appointments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="is_doctor",
            field=models.BooleanField(default=False, verbose_name="doctorStatus"),
        ),
    ]
