# Generated by Django 4.2.5 on 2023-10-24 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DoctorPortal", "0016_alter_patient_is_doctor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updaterUsername", models.CharField(default="", max_length=100)),
                ("diagnosis", models.CharField(default="", max_length=200)),
                ("docNotes", models.TextField(default="na")),
                ("lastUpdated", models.DateTimeField(auto_now=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosedPatient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staffUser",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosingDoctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
