# Generated by Django 4.2.5 on 2023-11-16 05:13

import django.core.validators
from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorPortal', '0017_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='apptDate',
            field=encrypted_model_fields.fields.EncryptedDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='docNotes',
            field=encrypted_model_fields.fields.EncryptedTextField(default='na'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patientNotes',
            field=encrypted_model_fields.fields.EncryptedTextField(default='na'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis',
            field=encrypted_model_fields.fields.EncryptedCharField(default=''),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='docNotes',
            field=encrypted_model_fields.fields.EncryptedTextField(default='na'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lname',
            field=encrypted_model_fields.fields.EncryptedCharField(default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=encrypted_model_fields.fields.EncryptedCharField(default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=encrypted_model_fields.fields.EncryptedPositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(130), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=encrypted_model_fields.fields.EncryptedTextField(default='na'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='history',
            field=encrypted_model_fields.fields.EncryptedTextField(default='na'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lname',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ssn',
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=encrypted_model_fields.fields.EncryptedTextField(default='na'),
        ),
    ]
