# Generated by Django 4.2.5 on 2023-11-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DoctorPortal", "0018_alter_patient_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="password",
            field=models.CharField(default="", max_length=129),
        ),
    ]
