# Generated by Django 4.2.5 on 2023-11-16 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorPortal', '0019_alter_appointments_apptdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='docNotes',
            field=models.TextField(default='na'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patientNotes',
            field=models.TextField(default='na'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='docNotes',
            field=models.TextField(default='na'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(130), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(default='na'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='history',
            field=models.TextField(default='na'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ssn',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.TextField(default='na'),
        ),
    ]
