# Generated by Django 4.2.5 on 2023-11-16 22:06

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorPortal', '0020_alter_appointments_docnotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='lname',
            field=encrypted_model_fields.fields.EncryptedCharField(default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=encrypted_model_fields.fields.EncryptedTextField(default='na'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='history',
            field=encrypted_model_fields.fields.EncryptedTextField(default='na'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=encrypted_model_fields.fields.EncryptedTextField(default='na'),
        ),
    ]
