# Generated by Django 4.2.5 on 2023-11-16 22:09

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorPortal', '0021_alter_doctor_lname_alter_patient_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='apptDate',
            field=encrypted_model_fields.fields.EncryptedDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='docNotes',
            field=encrypted_model_fields.fields.EncryptedTextField(default='na'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patientNotes',
            field=encrypted_model_fields.fields.EncryptedTextField(default='na'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='createdAt',
            field=encrypted_model_fields.fields.EncryptedDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis',
            field=encrypted_model_fields.fields.EncryptedCharField(default=''),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='docNotes',
            field=encrypted_model_fields.fields.EncryptedTextField(default='na'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='lastUpdated',
            field=encrypted_model_fields.fields.EncryptedDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patientdoctor',
            name='createdAt',
            field=encrypted_model_fields.fields.EncryptedDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patientdoctor',
            name='lastUpdated',
            field=encrypted_model_fields.fields.EncryptedDateTimeField(auto_now=True),
        ),
    ]
