# Generated by Django 4.2.5 on 2023-11-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorPortal', '0025_patient_otp_verification_secret_alter_patient_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='otp_verification_secret',
            field=models.CharField(default='', max_length=50),
        ),
    ]
