# Generated by Django 4.2.5 on 2023-11-24 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorPortal', '0025_alter_patient_ssn'),
        ('DoctorPortal', '0026_alter_patient_otp_verification_secret'),
    ]

    operations = [
    ]
